const GET_PRODUCTS = "GET_PRODUCTS";
const SELECT_PRODUCT = "SELECT_PRODUCT";
const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";

export { GET_PRODUCTS, SELECT_PRODUCT, REMOVE_SELECTED_PRODUCT };
